### ISSUE TITLE
Unitscan must not work during transport

### ISSUE THREAD

**Issue by SilverSaw** [Sattva-108/unitscan-TBC-2.4.3#1]
Addon must not scan when i take transport from flying master. Take Gryphon from SW to Westfall, you will see how addon is reacting on all rare units below.

**Comment by Sattva-108** [comment]
Hi check out new update. 
New commands available in `/unitscan help`
For taxi it's `/unitscan taxi` to disable/enable.

**Comment by SilverSaw** [comment]
Thanks, confirmed /unitscan taxi disabled function is working !
